import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react';
import NavBarView from '@/components/views/navbar/navbar';
import RoutingBar from '@/components/views/routingbar/routingbar';
import { NewRoutes } from '@/data/routes/routes'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Josh Rowley Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const routes = NewRoutes()
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBarView routes={routes}/>
        <RoutingBar routes={routes}/>
        {children}
      </body>
    </html>
  )
}
